# =============================================================================
# 10_GENERATE_FIGURE.R - Generate Figure 1: Temporal Meal Profiles
# =============================================================================
# Creates the main paper figure showing meal timing profiles by cluster
# for all 4 clustering methods with ABN nomenclature system
# Adapted from: figuras/generate_temporal_profiles_english.R
# Output: figure1_temporal_profiles.png (16x12 inches, 300 DPI)
# =============================================================================

library(tidyverse)
library(patchwork)
library(cowplot)

# Check for ggh4x (optional, not strictly required)
if (!requireNamespace("ggh4x", quietly = TRUE)) {
  cat("Note: ggh4x package not available, using standard facets\n")
}

cat("=== GENERATING FIGURE 1: TEMPORAL MEAL PROFILES ===\n\n")

# Create output directory
dir.create("output/figures", recursive = TRUE, showWarnings = FALSE)

# Load table summaries (generated by 09b_generate_summaries.R)
resumenes <- readRDS("output/data/table_summaries.rds")

# Combine all methods and rename columns
medianas_df <- bind_rows(
  resumenes$kmeans %>% mutate(metodo = "K-means"),
  resumenes$hierarchical %>% mutate(metodo = "Hierarchical"),
  resumenes$gmm %>% mutate(metodo = "GMM"),
  resumenes$spectral %>% mutate(metodo = "Spectral")
) %>%
  rename(
    desayuno_h = bf_med,
    comida_h = lunch_med,
    cena_h = dinner_med
  )

# =============================================================================
# ABN NOMENCLATURE SYSTEM (Predominance-Based Naming)
# =============================================================================
# P-codes (P1-P4) assigned by ranking median meal times within each method
# Tiebreaker: eating midpoint when clusters have equal median times
# Naming: Based on P-code appearing in 2+ meals (predominance)
# =============================================================================

# ABN classification function
medianas_df <- medianas_df %>%
  group_by(metodo) %>%
  mutate(
    # Calculate eating midpoint for tiebreaker
    eating_midpoint = (desayuno_h + cena_h) / 2
  ) %>%
  # Assign P-codes with tiebreaker
  arrange(desayuno_h, eating_midpoint) %>%
  mutate(P_breakfast = paste0("P", row_number())) %>%
  arrange(comida_h, eating_midpoint) %>%
  mutate(P_lunch = paste0("P", row_number())) %>%
  arrange(cena_h, eating_midpoint) %>%
  mutate(P_dinner = paste0("P", row_number())) %>%
  arrange(cluster) %>% # Restore original order
  mutate(
    position_code = paste(P_breakfast, P_lunch, P_dinner, sep = "-"),
    # ABN nomenclature based on predominance
    patron = case_when(
      # Early: P1 predominant (appears in 2+ meals)
      position_code %in%
        c("P1-P1-P1", "P2-P1-P1", "P1-P2-P1", "P1-P1-P2") ~ "Early",

      # Early-Intermediate: P2 predominant
      position_code %in%
        c(
          "P1-P2-P2",
          "P2-P2-P2",
          "P2-P1-P2",
          "P2-P2-P1",
          "P3-P2-P2",
          "P2-P3-P2",
          "P2-P2-P3"
        ) ~ "Early-Intermediate",

      # Late-Intermediate: P3 predominant
      position_code %in%
        c(
          "P3-P3-P3",
          "P4-P3-P3",
          "P3-P4-P3",
          "P3-P3-P4",
          "P2-P3-P3",
          "P3-P2-P3",
          "P3-P3-P2",
          "P1-P3-P3",
          "P3-P1-P3",
          "P3-P3-P1"
        ) ~ "Late-Intermediate",

      # Late: P4-P4-P4 only (consistently late)
      position_code == "P4-P4-P4" ~ "Late",

      # Late (early breakfast): P2-P4-P4 specifically
      position_code == "P2-P4-P4" ~ "Late (early breakfast)",

      TRUE ~ "Unknown"
    )
  ) %>%
  ungroup()

# Prepare data in long format
medianas_long <- medianas_df %>%
  pivot_longer(
    cols = c(desayuno_h, comida_h, cena_h),
    names_to = "meal_type",
    values_to = "time_h"
  ) %>%
  mutate(
    meal_type = factor(
      meal_type,
      levels = c("desayuno_h", "comida_h", "cena_h"),
      labels = c("Breakfast", "Lunch", "Dinner")
    ),
    patron = factor(
      patron,
      levels = c(
        "Early",
        "Early-Intermediate",
        "Late-Intermediate",
        "Late",
        "Late (early breakfast)"
      )
    ),
    metodo = factor(
      metodo,
      levels = c("K-means", "Hierarchical", "GMM", "Spectral")
    )
  )

# Function to convert decimal hour to HH:MM
decimal_to_hhmm <- function(decimal_hour) {
  hours <- floor(decimal_hour)
  minutes <- round((decimal_hour - hours) * 60)
  sprintf("%02d:%02d", hours, minutes)
}

# Add time label in HH:MM format
medianas_long <- medianas_long %>%
  mutate(time_label = sapply(time_h, decimal_to_hhmm))

# ABN Nomenclature Colors (Yellow -> Orange -> Blues -> Purple)
patron_colors <- c(
  "Early" = "#FDD835", # Yellow (earliest)
  "Early-Intermediate" = "#FFB74D", # Light orange
  "Late-Intermediate" = "#42A5F5", # Light blue
  "Late" = "#1565C0", # Dark blue (latest)
  "Late (early breakfast)" = "#7E57C2"
) # Purple (mixed pattern)

# =============================================================================
# GENERATE 3 SEPARATE PANELS (with custom axes)
# =============================================================================

# Function to format time as HH:MM
format_time_axis <- function(x) {
  hours <- floor(x)
  minutes <- round((x - hours) * 60)
  sprintf("%02d:%02d", hours, minutes)
}

# Panel 1: BREAKFAST (6-11h) - WITHOUT method names
fig_breakfast <- medianas_long %>%
  filter(meal_type == "Breakfast") %>%
  ggplot(aes(x = patron, y = time_h, color = patron, group = patron)) +
  geom_point(size = 6, alpha = 0.9) +
  geom_label(
    aes(label = time_label),
    size = 4,
    color = "black",
    fill = "white",
    alpha = 0.85,
    label.padding = unit(0.15, "lines"),
    label.size = 0.2,
    vjust = -0.6,
    fontface = "bold"
  ) +
  scale_color_manual(values = patron_colors, name = "Cluster name") +
  scale_y_continuous(
    limits = c(6, 11.5),
    breaks = seq(6, 11, by = 1),
    labels = format_time_axis
  ) +
  facet_grid(metodo ~ .) +
  labs(title = "Breakfast", x = NULL, y = "Time") +
  theme_minimal(base_size = 16) +
  theme(
    strip.text.y = element_blank(),
    strip.background = element_blank(),
    panel.border = element_rect(color = "gray70", fill = NA, linewidth = 0.5),
    panel.grid.minor = element_blank(),
    panel.spacing.y = unit(0.4, "lines"),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18)
  )

# Panel 2: LUNCH (14-18h) - WITHOUT method names
fig_lunch <- medianas_long %>%
  filter(meal_type == "Lunch") %>%
  ggplot(aes(x = patron, y = time_h, color = patron, group = patron)) +
  geom_point(size = 6, alpha = 0.9) +
  geom_label(
    aes(label = time_label),
    size = 4,
    color = "black",
    fill = "white",
    alpha = 0.85,
    label.padding = unit(0.15, "lines"),
    label.size = 0.2,
    vjust = -0.6,
    fontface = "bold"
  ) +
  scale_color_manual(values = patron_colors, name = "Cluster name") +
  scale_y_continuous(
    limits = c(13.5, 18.5),
    breaks = seq(14, 18, by = 1),
    labels = format_time_axis
  ) +
  facet_grid(metodo ~ .) +
  labs(title = "Lunch", x = NULL, y = NULL) +
  theme_minimal(base_size = 16) +
  theme(
    strip.text.y = element_blank(),
    strip.background = element_blank(),
    panel.border = element_rect(color = "gray70", fill = NA, linewidth = 0.5),
    panel.grid.minor = element_blank(),
    panel.spacing.y = unit(0.4, "lines"),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18)
  )

# Panel 3: DINNER (20-23h) - WITH method names on left
fig_dinner <- medianas_long %>%
  filter(meal_type == "Dinner") %>%
  ggplot(aes(x = patron, y = time_h, color = patron, group = patron)) +
  geom_point(size = 6, alpha = 0.9) +
  geom_label(
    aes(label = time_label),
    size = 4,
    color = "black",
    fill = "white",
    alpha = 0.85,
    label.padding = unit(0.15, "lines"),
    label.size = 0.2,
    vjust = -0.6,
    fontface = "bold"
  ) +
  scale_color_manual(values = patron_colors, name = "Cluster name") +
  scale_y_continuous(
    limits = c(19.5, 23.5),
    breaks = seq(20, 23, by = 1),
    labels = format_time_axis
  ) +
  facet_grid(metodo ~ .) +
  labs(title = "Dinner", x = NULL, y = NULL) +
  theme_minimal(base_size = 16) +
  theme(
    strip.text.y = element_text(angle = 0, hjust = 0, face = "bold", size = 12),
    strip.background = element_rect(fill = "gray95", color = "gray70", linewidth = 0.3),
    panel.border = element_rect(color = "gray70", fill = NA, linewidth = 0.5),
    panel.grid.minor = element_blank(),
    panel.spacing.y = unit(0.4, "lines"),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18)
  )

# =============================================================================
# COMBINE WITH LEGEND
# =============================================================================

# Create figure with temporary legend to extract it
fig_with_legend <- medianas_long %>%
  filter(meal_type == "Breakfast") %>%
  ggplot(aes(x = patron, y = time_h, color = patron)) +
  geom_point(size = 6) +
  scale_color_manual(values = patron_colors, name = "Cluster name") +
  theme_minimal(base_size = 16) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 13),
    legend.key.size = unit(1.4, "lines")
  ) +
  guides(color = guide_legend(nrow = 1, override.aes = list(size = 7)))

# Extract only the legend
legend <- cowplot::get_legend(fig_with_legend)

# Combine 3 panels horizontally with legend below
fig_combined <- (fig_breakfast | fig_lunch | fig_dinner) /
  cowplot::plot_grid(legend) +
  plot_layout(heights = c(10, 0.8), widths = c(1.15, 1, 1.15))

# =============================================================================
# SAVE FIGURE
# =============================================================================

output_path <- "output/figures/figure1_temporal_profiles.png"

ggsave(
  output_path,
  fig_combined,
  width = 16,
  height = 12,
  dpi = 300,
  bg = "white"
)

cat("Saved:", output_path, "\n")

# =============================================================================
# SUMMARY
# =============================================================================

cat("\n=== Figure 1 Summary ===\n")
cat("Dimensions: 16x12 inches, 300 DPI\n")
cat("Classification: ABN nomenclature (predominance-based P-codes)\n")
cat("Layout: 3 panels (Breakfast | Lunch | Dinner)\n")
cat("Methods: Labels only on Dinner panel (right side)\n")
cat("Y-axes: Independent by panel:\n")
cat("  - Breakfast: 06:00-11:00\n")
cat("  - Lunch: 14:00-18:00\n")
cat("  - Dinner: 20:00-23:00\n")
cat("Colors: Yellow (Early) -> Orange -> Light Blue -> Dark Blue -> Purple\n")

cat("\n=== FIGURE 1 GENERATION COMPLETE ===\n")
