# =============================================================================
# Script: 08_table_S2_cluster_profiles.R
# Purpose: Generate Table S2 with cluster profiles showing Median [Q1,Q3]
# Author: Generated by Claude Code
# Date: 2025-12-02
# Output: tableS2_cluster_profiles_all_k.tex, tableS2_cluster_profiles_all_k.csv
# =============================================================================

cat("=== Generating Table S2: Cluster Profiles with Median [Q1,Q3] ===\n\n")

# -----------------------------------------------------------------------------
# SETUP
# -----------------------------------------------------------------------------

library(dplyr)
library(mclust)
library(kernlab)

# Create output directories
dir.create("output/tables", recursive = TRUE, showWarnings = FALSE)

# -----------------------------------------------------------------------------
# LOAD DATA
# -----------------------------------------------------------------------------

cat("Loading prepared data...\n")
prepared <- readRDS("output/data/prepared_data.rds")
datos_raw <- prepared$datos_clustering[, prepared$vars_clustering]
datos_scaled <- as.matrix(prepared$datos_scaled)

cat("  - n =", nrow(datos_raw), "participants\n\n")

# -----------------------------------------------------------------------------
# HELPER FUNCTIONS
# -----------------------------------------------------------------------------

# Convert decimal hours to HH:MM format
decimal_to_time <- function(hours) {
  h <- floor(hours)
  m <- round((hours - h) * 60)
  # Handle case where rounding gives 60 minutes
  if (m == 60) {
    h <- h + 1
    m <- 0
  }
  sprintf("%02d:%02d", h, m)
}

# Format time with IQR: "HH:MM [Q1,Q3]"
format_time_iqr <- function(median_val, q25_val, q75_val) {
  sprintf("%s [%s,%s]",
          decimal_to_time(median_val),
          decimal_to_time(q25_val),
          decimal_to_time(q75_val))
}

# Calculate median and IQR for each cluster
calc_profile_stats <- function(datos_raw, clusters) {
  vars <- colnames(datos_raw)

  result <- datos_raw %>%
    mutate(cluster = clusters) %>%
    group_by(cluster) %>%
    summarise(
      n = n(),
      across(all_of(vars), list(
        median = ~median(., na.rm = TRUE),
        q25 = ~quantile(., 0.25, na.rm = TRUE),
        q75 = ~quantile(., 0.75, na.rm = TRUE)
      )),
      .groups = "drop"
    )

  return(result)
}

# -----------------------------------------------------------------------------
# RUN CLUSTERING FOR ALL K AND METHODS
# -----------------------------------------------------------------------------

cat("Running clustering for k=2 to k=5...\n")

methods <- c("K-means", "Hierarchical", "GMM", "Spectral")
k_values <- 2:5

all_profiles <- data.frame()

for (k in k_values) {
  cat(sprintf("  k = %d: ", k))

  # K-means
  set.seed(2025)
  km <- kmeans(datos_scaled, centers = k, nstart = 50, iter.max = 1000)
  km_stats <- calc_profile_stats(datos_raw, km$cluster)
  km_stats$Method <- "K-means"
  km_stats$k <- k
  cat("K-means ")

  # Hierarchical
  dist_matrix <- dist(datos_scaled)
  hc <- hclust(dist_matrix, method = "ward.D2")
  hc_clusters <- cutree(hc, k = k)
  hc_stats <- calc_profile_stats(datos_raw, hc_clusters)
  hc_stats$Method <- "Hierarchical"
  hc_stats$k <- k
  cat("Hier ")

  # GMM
  set.seed(2025)
  gmm <- Mclust(datos_scaled, G = k, verbose = FALSE)
  gmm_stats <- calc_profile_stats(datos_raw, gmm$classification)
  gmm_stats$Method <- "GMM"
  gmm_stats$k <- k
  cat("GMM ")

  # Spectral
  set.seed(2025)
  spec <- specc(datos_scaled, centers = k)
  spec_stats <- calc_profile_stats(datos_raw, spec@.Data)
  spec_stats$Method <- "Spectral"
  spec_stats$k <- k
  cat("Spectral\n")

  all_profiles <- bind_rows(all_profiles, km_stats, hc_stats, gmm_stats, spec_stats)
}

# Reorder columns
vars <- prepared$vars_clustering
all_profiles <- all_profiles %>%
  dplyr::select(k, Method, cluster, n, everything())

# -----------------------------------------------------------------------------
# FORMAT FOR DISPLAY
# -----------------------------------------------------------------------------

cat("\nFormatting output...\n")

# Create formatted columns
all_profiles <- all_profiles %>%
  mutate(
    Breakfast_fmt = mapply(format_time_iqr,
                           breakfast_time_median,
                           breakfast_time_q25,
                           breakfast_time_q75),
    Lunch_fmt = mapply(format_time_iqr,
                       lunch_time_median,
                       lunch_time_q25,
                       lunch_time_q75),
    Dinner_fmt = mapply(format_time_iqr,
                        dinner_time_median,
                        dinner_time_q25,
                        dinner_time_q75)
  )

# -----------------------------------------------------------------------------
# SAVE CSV
# -----------------------------------------------------------------------------

# Save full data
write.csv(all_profiles, "output/tables/tableS2_cluster_profiles_all_k.csv", row.names = FALSE)
cat("Saved: output/tables/tableS2_cluster_profiles_all_k.csv\n")

# -----------------------------------------------------------------------------
# PRINT SUMMARY
# -----------------------------------------------------------------------------

cat("\n=== Cluster Profiles Summary (Median [Q1,Q3]) ===\n")

for (k in k_values) {
  cat(sprintf("\n--- k=%d%s ---\n", k, if (k == 4) " (SELECTED)" else ""))
  profiles_k <- all_profiles[all_profiles$k == k, ]

  for (method in methods) {
    method_data <- profiles_k[profiles_k$Method == method, ]
    method_data <- method_data[order(method_data$cluster), ]
    cat(sprintf("  %s:\n", method))
    for (j in 1:nrow(method_data)) {
      row <- method_data[j, ]
      cat(sprintf("    C%d (n=%d): BF=%s, L=%s, D=%s\n",
                  row$cluster, row$n,
                  row$Breakfast_fmt, row$Lunch_fmt, row$Dinner_fmt))
    }
  }
}

cat("\n=== Table S2 generation complete ===\n")
